updated

diff --git a/mkinitramfs b/mkinitramfs
--- a/mkinitramfs
+++ b/mkinitramfs
@@ -24,9 +24,18 @@ copy()
   fi
 }
 
+msg() {
+	echo ":: $@"
+}
+
+msgerr() {
+	echo "ERROR: $@"
+}
+
 interrupted() {
 	cleanup
-	echo; echo "Aborted by user!"
+	echo
+	msgerr "Aborted by user!"
 	exit 1
 }
 
@@ -41,13 +50,13 @@ Usage:
   $(basename $0) <option> <argument>
 
 Options:
-  -k <arg>  custom kernel version
-  -o <arg>  custom output name
-  -i <arg>  use custom init file
-  -n        dont copy kernel modules
-  -f        dont copy firmware
-  -h        print this help msg
-  -m        loaded modules only
+  -k|--kernver    <arg>  custom kernel version
+  -o|--output     <arg>  custom output name
+  -i|--init       <arg>  custom init file
+  -f|--firmware          include firmware
+  -n|--no-modules        exclude kernel modules
+  -m|--modules           include loaded modules only
+  -h|--help              print this help msg
 	
 EOF
 }
@@ -56,39 +65,44 @@ trap "interrupted" SIGHUP SIGINT SIGQUIT SIGTERM
 
 while [ $1 ]; do
 	case $1 in
-		-k) KERNEL=$2
-			if [ -z $2 ]; then
-				echo "argument is needed for this option"
-				exit 1
-			fi
-			shift 2 ;;
-		-o) OUTPUT=$2
-			if [ -z $2 ]; then
-				echo "argument is needed for this option"
-				exit 1
-			fi
-			shift 2 ;;
-		-i) INIT=$2
-			if [ -z $2 ]; then
-				echo "argument is needed for this option"
-				exit 1
-			fi
-			shift 2 ;;
-		-m) LOADEDMOD=1
-			shift ;;
-		-n) NOKMOD=1
-			shift ;;
-		-f) NOFIRMWARE=1
-			shift ;;
-		-h) usage
-			exit 0 ;;
-		*) echo "ERROR: invalid '$1' option"
-			exit 1 ;;
+		-k|--kernver)	if [ -z $2 ]; then
+							echo "argument is needed for this option"
+							exit 1
+						fi
+						KERNEL=$2
+						shift 2 ;;
+		-o|--output)	if [ -z $2 ]; then
+							echo "argument is needed for this option"
+							exit 1
+						fi
+						OUTPUT=$2
+						shift 2 ;;
+		-i|--init)		if [ -z $2 ]; then
+							echo "argument is needed for this option"
+							exit 1
+						fi
+						INIT=$2
+						shift 2 ;;
+		-m|--modules)	LOADEDMOD=1
+						shift ;;
+		-n|--no-modules) NOKMOD=1
+						shift ;;
+		-f|--firmware)	FIRMWARE=1
+						shift ;;
+		-h|--help)		usage
+						exit 0 ;;
+		*)				echo "ERROR: invalid option '$1'"
+						exit 1 ;;
 	esac
 done
 
+if [ "$UID" != "0" ]; then
+	msgerr "need root access!"
+	exit 1
+fi
+
 if [ ! -d  ]; then
-	echo "ERROR: directory  does not exist!"
+	msgerr "directory  does not exist!"
 	exit 1
 fi
 
@@ -96,7 +110,7 @@ if [ "$KERNEL" ]; then
 	if [ -d /lib/modules/"$KERNEL" ]; then
 		KERNEL_VERSION="$KERNEL"
 	else
-		echo "ERROR: kernel directory '/lib/modules/$KERNEL' not exist"
+		msgerr "kernel directory '/lib/modules/$KERNEL' not exist"
 		exit 1
 	fi
 else
@@ -124,7 +138,7 @@ else
 fi
 
 if [ ! -f "$INITIN" ]; then
-	echo "ERROR: file init '$INITIN' not exist"
+	msgerr "file init '$INITIN' not exist"
 	exit 1
 fi
 
@@ -145,11 +159,11 @@ done
 unsorted=$(mktemp /tmp/unsorted.XXXXXXXXXX)
 
 # Create a temporary working directory
-echo " creating working directory..."
+msg "creating working directory..."
 WDIR=$(mktemp -d /tmp/initrd-work.XXXXXXXXXX)
 
 # Create base directory structure
-echo " creating base structure directory..."
+msg "creating base structure directory..."
 mkdir -p $WDIR/{bin,dev,lib/firmware,run,sys,proc,usr}
 mkdir -p $WDIR/etc/{modprobe.d,udev/rules.d}
 touch $WDIR/etc/modprobe.d/modprobe.conf
@@ -159,12 +173,12 @@ ln -s bin $WDIR/sbin
 ln -s ../bin $WDIR/usr/sbin
 
 # Create necessary device nodes
-echo " creating device nodes..."
+msg "creating device nodes..."
 mknod -m 640 $WDIR/dev/console c 5 1
 mknod -m 664 $WDIR/dev/null    c 1 3
 
 # Install the udev configuration files
-echo " copying udev configuration..."
+msg "copying udev configuration..."
 if [ -f /etc/udev/udev.conf ]; then
 	cp /etc/udev/udev.conf $WDIR/etc/udev/udev.conf
 fi
@@ -190,19 +204,19 @@ elif [ -x /lib/systemd/systemd-udevd ] ; then
 fi
 
 # Install firmware
-if [ "$NOFIRMWARE" != 1 ]; then
-	echo " copying firmware..."
+if [ "$FIRMWARE" = 1 ]; then
+	msg "copying firmware..."
 	cp -a /lib/firmware $WDIR/lib
 fi
 
 # Copy the RAID configuration file if present
 if [ -f /etc/mdadm.conf ] ; then
-	echo " copying raid configuration..."
+	msg "copying raid configuration..."
 	cp /etc/mdadm.conf $WDIR/etc
 fi
 
 # Install the init file
-echo " copying init file..."
+msg "copying init file..."
 install -m0755 $INITIN $WDIR/init
 
 if [ "$NOKMOD" != 1 ]; then
@@ -217,7 +231,7 @@ fi
 # Add lvm if present
 if [ -x /sbin/lvm ] ; then binaries="$binaries lvm dmsetup"; fi
 
-echo " copying basic binaries..."
+msg "copying binaries..."
 for i in $binaries; do
 	copy $i bin
 	ldd $(PATH=/bin:$ROOT/usr/bin:$ROOT/sbin:$ROOT/usr/sbin type -p $i) | sed "s/\t//" | cut -d " " -f1 >> $unsorted
@@ -255,7 +269,7 @@ if  [ -x /sbin/lvm ] ; then
 fi
 
 # Install libraries
-echo " copying library..."
+msg "copying libraries..."
 sort $unsorted | uniq | grep -v ^not$ | while read library ; do
 	if [ "$library" == "linux-vdso.so.1" ] || [ "$library" == "linux-gate.so.1" ]; then
 		continue
@@ -265,7 +279,7 @@ done
 
 # copy terminfo
 if [ -d /usr/share/terminfo ]; then
-	echo " copying terminfo..."
+	msg "copying terminfo..."
 	mkdir -p $WDIR/usr/share
 	cp -r /usr/share/terminfo $WDIR/usr/share/
 fi
@@ -273,12 +287,12 @@ fi
 # Install the kernel modules if requested
 if [ "$NOKMOD" != 1 ]; then
 	if [ "$LOADEDMOD" = 1 ]; then
-		echo " copying loaded modules..."
+		msg "copying loaded modules..."
 		for k in $(lsmod | awk '{print $1}'); do
 			find /lib/modules/$KERNEL_VERSION/kernel/ -name $k.ko* -type f | cpio --make-directories -p --quiet $WDIR
 		done
 	else
-		echo " copying all modules..."
+		msg "copying all modules..."
 		find /lib/modules/$KERNEL_VERSION/kernel/ \
 		 -name *.ko* -type f 2> /dev/null | cpio --make-directories -p --quiet $WDIR
 	fi
@@ -288,12 +302,12 @@ if [ "$NOKMOD" != 1 ]; then
 	depmod -b $WDIR $KERNEL_VERSION
 fi
 
-echo " compressing initramfs..."
+msg "compressing initramfs..."
 rm -f $INITRAMFS_FILE
 ( cd $WDIR ; find . | cpio -o -H newc --quiet | gzip -9 ) > $INITRAMFS_FILE
 
 # Remove the temporary directory and file
 cleanup
-echo "done"
+echo "Done"
 
 exit 0
